### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by octopitus** [octopitus/rn-sliding-up-panel#79]
##### Edit:
- Published on npm under `next` tag (`npm install rn-sliding-up-panel@next`).

---

Hi forks,

Sorry I haven't actively maintained this package for a while. It was a hard time for me recently. This is to keep track the current process of the second release. Please take a look if you come over.

- Pull request: https://github.com/octopitus/rn-sliding-up-panel/pull/80

## Breaking changes:

- [x] Remove the `visible` and `onRequestClose` props.  The component now will always be rendered, below the screen. Use `show()` & `hide()` to control panel position.

## New features:
- [x] Animated value is now configurable. Means you can control how the panel appears & disappears with Animated.timing, Animated.spring, Animated.decay.
- [x] Expose more props to enhance effects (Initial velocity, friction, minimum velocity & distance threshold, etc...).
- [x] Support screen orientation.
- [x] Compatible with `react-native-web` ([Demo](https://codesandbox.io/s/3440ox733m))
- [ ] ~Panel can be pulled up from the bottom of screen.~

## Issues fixed:
- [x] The component now will automatically reacts to the keyboard events. This will fix several issues: https://github.com/octopitus/rn-sliding-up-panel/issues/53, https://github.com/octopitus/rn-sliding-up-panel/issues/32, https://github.com/octopitus/rn-sliding-up-panel/issues/67.
- [x] `onDragEnd` should be fired when the pan responder is terminated: https://github.com/octopitus/rn-sliding-up-panel/issues/82
- [x] Fix issue `height` property can not be changed: https://github.com/octopitus/rn-sliding-up-panel/issues/74

**Comment by Jelomite** [comment]
Good to see you're able to maintain the package, it's not something trivial. :smile: 
May I ask,  what's the reason behind the first decision of always rendering the component instead of the current behavior?

**Comment by octopitus** [comment]
Nope. It won't affect the lifecycle of the component inside panel.

**Comment by Jelomite** [comment]
I see, than in that case, I think your new approach is quite elegant, thanks for the explanation 👍

**Comment by PurnimaNaik** [comment]
@octopitus Any idea by when the README will be updated?

**Comment by octopitus** [comment]
Updated https://github.com/octopitus/rn-sliding-up-panel/tree/v2

**Comment by PurnimaNaik** [comment]
It says - 
`_this2._panel.show is not a function. (In '_this2._panel.show()', '_this2._panel.show' is undefined)`

Am I doing something wrong? v1 was working right out the box..I did the exact same for v2 but I am getting the above mentioned error..

Do I need to write the function myself?

**Comment by octopitus** [comment]
Thanks for pointing that out @colaskirschoff. If possible can you create a PR to express the issue? Much appreciated.

**Comment by colaskirschoff** [comment]
Just did it, let me know if it works for you :)

**Comment by VenomApps** [comment]
Why is there no useNativeDriver?

**Comment by octopitus** [comment]
@VenomApps Answered here: https://github.com/octopitus/rn-sliding-up-panel/issues/50#issuecomment-464589596
